/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controladoras.LamparasDAO;
import controladoras.VentasDAO;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.scripts.JO;
import modelos.Lamparas;

import org.omg.CORBA.INTERNAL;

/**
 *
 * @author AUL-USR-I-SJL333
 */
public class FrmVender extends javax.swing.JFrame {
    
   
    
    LamparasDAO obj = new LamparasDAO();

    public void pCargarModelosAlCombo(){
        int cantElemVector = LamparasDAO.vLamparas.size();
       
        for(int x = 0; x < cantElemVector; x++){
            Lamparas objRecueprado = new Lamparas();//Está vacío
            objRecueprado = (Lamparas) LamparasDAO.vLamparas.elementAt(x);
            
            cbo_modelo.addItem(  objRecueprado.getModelo()  );
        }
        
      
    }
    
    
    public FrmVender() {
        initComponents();
        
        pCargarModelosAlCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cerar = new javax.swing.JButton();
        lbl_modelo = new javax.swing.JLabel();
        lbl_precios = new javax.swing.JLabel();
        cbo_modelo = new javax.swing.JComboBox<>();
        txt_precio = new javax.swing.JTextField();
        btn_vender = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_salida = new javax.swing.JTextArea();
        lbl_cantidad = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("vender");

        btn_cerar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_cerar.setText("Cerrar");
        btn_cerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerarActionPerformed(evt);
            }
        });

        lbl_modelo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_modelo.setText("Modelo");

        lbl_precios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_precios.setText("Precio (S/)");

        cbo_modelo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbo_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_modeloActionPerformed(evt);
            }
        });

        txt_precio.setEditable(false);
        txt_precio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btn_vender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_vender.setText("Vender");
        btn_vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_venderActionPerformed(evt);
            }
        });

        txt_salida.setEditable(false);
        txt_salida.setColumns(20);
        txt_salida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_salida.setRows(5);
        jScrollPane1.setViewportView(txt_salida);

        lbl_cantidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_cantidad.setText("Cantidad");

        txt_cantidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_precios)
                            .addComponent(lbl_modelo)
                            .addComponent(lbl_cantidad))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbo_modelo, 0, 241, Short.MAX_VALUE)
                            .addComponent(txt_precio)
                            .addComponent(txt_cantidad))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(btn_vender, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cerar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_modelo)
                    .addComponent(cbo_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_vender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_precios))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(btn_cerar)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_cantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_cerarActionPerformed

    private void cbo_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_modeloActionPerformed
        // TODO add your handling code here:
        int nroFilaSeleccionada = cbo_modelo.getSelectedIndex();
        
        Lamparas obj = new Lamparas();//Está vacío
        obj = (Lamparas) LamparasDAO.vLamparas.elementAt(nroFilaSeleccionada);

         txt_precio.setText(  "" + obj.getPrecio()  );
    
     
    }//GEN-LAST:event_cbo_modeloActionPerformed

    private void btn_venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_venderActionPerformed

        int cantidad = Integer.parseInt(txt_cantidad.getText());
        String modelo = cbo_modelo.getSelectedItem().toString();
        double precio = Double.parseDouble(txt_precio.getText());
        double importe = (cantidad*precio);
        double descuento = 0; 
        int nromodelo=cbo_modelo.getSelectedIndex();
        int posicion;
        posicion = cbo_modelo.getSelectedIndex();
        
        
        Lamparas obj1 = new Lamparas();
         obj1.setPrecio(precio);
       
        
    VentasDAO.ventas(txt_salida, cantidad, modelo, importe, precio, descuento,nromodelo);
    

      
    }//GEN-LAST:event_btn_venderActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerar;
    private javax.swing.JButton btn_vender;
    private javax.swing.JComboBox<String> cbo_modelo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_modelo;
    private javax.swing.JLabel lbl_precios;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextArea txt_salida;
    // End of variables declaration//GEN-END:variables
}
